@url = http://localhost:8000

### signup
POST {{url}}/auth/signup/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "email": "deneme2@mail.com",
    "password": "P4ssword.",
    "username": "deneme2",
    "first_name": "deneme2",
    "last_name": "deneme2",
    "avatar_url": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"
}

###
GET {{url}}/auth/verify-account/8ab62074-c57c-4a0c-bf39-3288a4838e88 HTTP/1.1
Accept-Language: tr

###
# @name signin
POST {{url}}/auth/signin/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "signin": "deneme1@mail.com",
    "password": "P4ssword."
}

###
# @name signout
GET {{url}}/auth/signout/ HTTP/1.1
Accept-Language: tr
Authorization: Bearer {{signin.response.body.data.access_token.token}}

###
# @name refresh
GET {{url}}/auth/refresh-token/ HTTP/1.1
Accept-Language: tr
Authorization: Bearer {{refresh.response.body.data.refresh_token.token}}
