@url = http://localhost:8000/api

### signup
POST {{url}}/auth/signup/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "email": "selahattingungor53@hotmail.com",
    "password": "P4ssword.",
    "username": "selahattin111",
    "first_name": "selahattin1",
    "last_name": "selahattin1",
    "avatar_url": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"
}

### verify-account
GET {{url}}/auth/verify-account/429b8155-6328-4d9b-a084-bd22a2b26a89 HTTP/1.1
Accept-Language: tr

### retry-verify-account
POST {{url}}/auth/retry-verify-account/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "email": "selahattingungor053@gmail.com"
}

### signin
# @name signin
POST {{url}}/auth/signin/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "signin": "selahattin11",
    "password": "P4ssword."
}

### signout
# @name signout
GET {{url}}/auth/signout/ HTTP/1.1
Accept-Language: tr
Authorization: Bearer {{signin.response.body.data.access_token.token}}

### refresh
# @name refresh
GET {{url}}/auth/refresh-token/ HTTP/1.1
Accept-Language: tr
Authorization: Bearer {{refresh.response.body.data.refresh_token.token}}
