@url = http://localhost:8000

### signup
POST {{url}}/auth/signup/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "email": "selahattingungor053@gmail.com",
    "password": "P4ssword.",
    "username": "deneme123",
    "first_name": "deneme1",
    "last_name": "deneme1",
    "avatar_url": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"
}

### verify-account
GET {{url}}/auth/verify-account/70984b2f-6e99-437b-8048-a7ee0e1a97b4 HTTP/1.1
Accept-Language: tr

### retry-verify-account
POST {{url}}/auth/retry-verify-account/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "email": "selahattingungor053@gmail.com"
}

### signin
# @name signin
POST {{url}}/auth/signin/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "signin": "segungor",
    "password": "Sg27.09.2000"
}

### signout
# @name signout
GET {{url}}/auth/signout/ HTTP/1.1
Accept-Language: tr
Authorization: Bearer {{signin.response.body.data.access_token.token}}

### refresh
# @name refresh
GET {{url}}/auth/refresh-token/ HTTP/1.1
Accept-Language: tr
Authorization: Bearer {{refresh.response.body.data.refresh_token.token}}
