@url = http://localhost:8000

###
# @name signin
POST {{url}}/auth/signin/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "signin": "bege",
    "password": "123Gursoy123"
}

###
# @name signin
POST {{url}}/auth/two-factor/ HTTP/1.1
Accept-Language: tr
Accept: application/json

{
    "username": "bege",
    "code": "8784"
}

###
# @name get_history
GET {{url}}/api/game/get-history/bege/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlbGFoYXR0aW4iLCJleHAiOjE3NjU0MDIxMjd9.rvFJyy0QsPja2JokOndWzd5JydwisPug-VySdoIrDjU

###
# @name save_game
POST {{url}}/api/game/save-game/ HTTP/1.1
Accept-Language: tr
Accept: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlbGFoYXR0aW4iLCJleHAiOjE3NjU0MDIxMjd9.rvFJyy0QsPja2JokOndWzd5JydwisPug-VySdoIrDjU

{
    "username": "selahattin",
    "userScore": 1,
    "aiScore": 5,
    "isWin": false
}