services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: selahattin
      POSTGRES_PASSWORD: selahattin31
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pg_data:

networks:
  postgres-network:
    driver: bridge
