services:
  frontend:
    container_name: frontend
    build: ./dumendenforont
    env_file:
      - .env
    hostname: frontend
    ports:
      - "3000:3000"
    networks:
      - backend

  apigateway:
    container_name: apigateway
    build: ./apigateway
    env_file:
      - .env
    hostname: apigateway
    ports:
      - "8000:8000"
    networks:
      - backend
  authservice:
    container_name: authservice
    build: ./auth_service
    env_file:
      - .env
    hostname: authservice
    networks:
      - backend
  userservice:
    container_name: userservice
    build: ./user_service
    env_file:
      - .env
    hostname: userservice
    networks:
      - backend
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge